### ISSUE TITLE
[Feature Request] Add scripts from pipenv Pipfile for Python

### ISSUE THREAD

**Issue by Rob4226** [spmeesseman/vscode-taskexplorer#155]
Hi,
This is an excellent extension, I use it every day, so thank you!  I would like to make a feature request for Python to run scripts from the `[scripts]` section in a `Pipfile` file that is used with the [`pipenv`](https://github.com/pypa/pipenv) Python package manager.  Below is an example of a `Pipenv` file. It is analogous to a "package.json" file for `npm`.  Note that the `Pipfile` uses the `TOML` Spec.

Pipenv scripts docs: https://pipenv.pypa.io/en/latest/advanced/#custom-script-shortcuts

I will try to start working on it myself but just wanted to make a post about it bc the `[scripts]` section seems like a perfect fit for this extension.

To run a pipenv script you do: `pipenv run <name of script>` so using the below example file `pipenv run build-exe`
To list all scripts you can run `pipenv scripts`

`Pipenv` file example (users TOML format):
```TOML
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
pyside6 = "*"
mypy = "*"
paramiko = "*"
pyinstaller = {extras = ["encryption"], version = "*"}

[dev-packages]
isort = "*"
flake8 = "*"
pyinstaller = "*"

[requires]
python_version = "3.9"

[scripts]
convert-ui = "pyside6-uic ui_mainwindow.ui > ui_mainwindow.py"
build-exe = "pyinstaller --name='RobPySSHgui' --windowed --onefile ./main.py"
run-dev = "python main.py"
```
